version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: greetings
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql

  spring-boot-app:
    image: spring-boot-mysql-docker-demo:latest
    container_name: spring-boot-container
    depends_on:
      - mysql
    networks:
        - spring-mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/greetings?useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  mysql-data:
networks:
  spring-mysql:
